baseurl = "https://needleinthehay.ca/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Needle in the Hay"
theme = "beautifulhugo"
paginate = 5
PaginatePath = "post"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
  post = "/:year/:month/:day/:slug/"

[Params]
  homeTitle = "Needle in the Hay" # Set a different text for the header on the home page
  subtitle = "A Data and Analytics Blog"
  logo = "img/hmd2.png"
  favicon = ""
  dateFormat = "2006/01/02"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/mntn.jpg"
#  desc = ""
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Hayden MacDonald"
  email = "hayden.macdonald.8778@gmail.com"
  github = "/HaydenMacDonald"
  twitter = "/HYDNMCDNLD"
  linkedin = "hayden-macdonald/"

[[menu.main]]
    name = "Blog"
    pre = "<i> class='fa fa-list fa-fw'></i>"
    url = "/post/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2


[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3